# Generated by Django 4.2.23 on 2025-08-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models3d', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threedmodel',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
